### ISSUE TITLE
Using the Ref-NeRF codebase to reproduce the table in the paper.

### ISSUE THREAD

**Issue by 78ij** [google-research/multinerf#32]
Firstly, thanks for the authors' impressive work!
I am currently trying to reproduce Table S6-S9 in the original Ref-NeRF paper(the shiny blender dataset). I am currently using the shinyblender config in the repository.
**However, when testing with the "ball' dataset, the results is not as good as the paper shows**(precisely, the paper show a PSNR of ~47, but in my case, after 250000 iterations, the PSNR barely reaches 39 in training, and the images rendered look far from the GT). Really confused by the results.
![1](https://user-images.githubusercontent.com/13299678/187109928-ab134ede-0e3d-4fe7-8755-395ecb700655.png)
![2](https://user-images.githubusercontent.com/13299678/187109937-2d68280b-6f40-42e2-962c-6a09755c2f9e.png)
![3](https://user-images.githubusercontent.com/13299678/187109943-da4af0ae-be3d-467f-8248-9cda7a38ad6f.png)
![4](https://user-images.githubusercontent.com/13299678/187109947-5af764fe-0226-48ee-81a0-454eafa1b8ea.png)

**Comment by jonbarron** [comment]
Weird, it looks like it's not getting fully opaque. 

Looking at our result in generate_tables, it looks like when we ran this code on this scene we also got 38 PSNR. I don't remember the results looking this bad visually though. Note that this code release isn't identical to what we used in the paper (this is basically a re-implementation of ref-nerf inside the mipnerf360 codebase).

This particular scene is tricky because the scene is easy enough that ref-nerf is able to get extremely low error rates (note that 47 and 38 PSNR are both extremely high numbers that correspond to extremely small MSE values). I think something small in the code is causing it to fall into a different local minimum across different runs. You might want to try tweaking the hyperparams to see if it falls into a different local minimum if you really care about the performance of this scene. Or I would just focus on a different scene, as this scene is extremely synthetic and "toy".

**Comment by 78ij** [comment]
> Weird, it looks like it's not getting fully opaque.
> 
> Looking at our result in generate_tables, it looks like when we ran this code on this scene we also got 38 PSNR. I don't remember the results looking this bad visually though. Note that this code release isn't identical to what we used in the paper (this is basically a re-implementation of ref-nerf inside the mipnerf360 codebase).
> 
> This particular scene is tricky because the scene is easy enough that ref-nerf is able to get extremely low error rates (note that 47 and 38 PSNR are both extremely high numbers that correspond to extremely small MSE values). I think something small in the code is causing it to fall into a different local minimum across different runs. You might want to try tweaking the hyperparams to see if it falls into a different local minimum if you really care about the performance of this scene. Or I would just focus on a different scene, as this scene is extremely synthetic and "toy".

Thanks for your quick reply. In fact, the metrics are indeed better in other scenes(eg. helmet, teapot), and the geometry is better too. I totally agree with you that this scene is a 'testing stub', which is not so important. I guess i should move to other complicated scenes (I observed that in NeRF context, simple scenes do not always mean easy learnt :( )
I am closing this issue, thanks again for your reply.

**Comment by Dharmendra04** [comment]
Hi, where did you find this shiny blender dataset?, and which is the configuration used for shiny blender dataset from the following configuration files.

<img width="1107" alt="Screenshot 2023-09-09 at 14 09 21" src="https://github.com/google-research/multinerf/assets/108211571/2d9c5c24-a523-466b-b6ad-9680bc03398e">
